### ISSUE TITLE
Get signatures through IPFS

### ISSUE THREAD

**Issue by branimirangelov** [comrade-coop/apocryph#2]
Make Input/Output smarter by sending only Hash/Key/Signature, maybe even try to get actual signatures from IPFS

**Comment by bojidar-bg** [comment]
The main part of this issue (sending only the hash of the data) was actually done with 80a81df740976ced901eaccb9338c2743b4c56de.

I'm going to retitle the issue so that it is only about getting keys and signatures through IPFS.

**Comment by bojidar-bg** [comment]
I worked around the issue in 626f3037f3206b3e13d313cdac3a8f37c404af98, by basing the KoTH on hashes instead of actual keys. The question of getting actual signatures from IPFS or pumping in already signed data remains open.

As the finalization network is going to require ECDsa keys, we can resort to sending signed messages or signatures within the IPFS PubSub envelope. However, this is not exactly optimal for the general case, as no one should need to care about the exact IPFS peer from which the message originated.
